on:
    push:
      branches:
        - main
name: CI
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: install cargo make
          uses: taiki-e/install-action@370d6b7a85900451456cc58b71ebdbe965d20d8e
          with:
            tool: cargo-make
        - name: cargo make test
          run: cargo make test
    